name: Generate streak stats

on:
  schedule:
    - cron: "10 5 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout assets branch
        uses: actions/checkout@v4
        with:
          ref: assets

      - name: Generate streak stats card
        uses: DenverCoder1/github-readme-streak-stats@a15ea3616bbfb93936eba475b3de9da1c8900633 # main
        with:
          options: >-
            user=${{ github.repository_owner }}&theme=dark&hide_border=true&background=0D1117&ring=39FF88&fire=FF2E88&currStreakLabel=39FF88

      - name: Commit streak stats
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/streak.svg
          git commit -m "Update streak stats" || exit 0
          git push
